---
- hosts: localhost
  remote_user: ubuntu
  tasks:

    - name: Enure the group "admin" exists
      become: true
      become_method: sudo
      group:
        name: "{{ item }}"
        state: present
      with_items:
         - admins
         - developers
         - wheel
    
    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'



    - include: pre_puppet_users.yml
#    - include: developers.yml
#    - name: create the user 
#      become: true
#      become_method: sudo 
#      command:  adduser --disabled-password --force-badname  --gecos "" "{{ item.name}}"
#      with_items: 
#        - "{{admins}}" 
#        - "{{developers}}"
  

    - name:  create the authorized keys and  and append for the users
      authorized_key:
        user: "{{ item.name }}"
        state: present
        key:  "{{item.keys}}"
      with_items: 
        - "{{pre_puppet_users.yml}}"
      



    - name: add the users  with bash shell and appending the group 'admin'
      become: true
      become_method: sudo
      user:
        name: "{{ item.username}}"
        groups: admins,wheel
        append: yes
      with_items: "{{ admins }}"  

    - name: add the  users  with bash shell and append the group 'developer'
      become: true
      become_method: sudo 
      user: 
        name:  "{{ item.username}}"
        groups: developers
        apppend: yes
      with_items: "{{developers}}" 
     
    
